[package]
name = "excercises"
version = "0.1.0"
authors = ["Konrad Sosnowski <konrad.sosnowski@ubnt.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
itertools = "0.10.0"
regex = "1.4.5"